import json
from pathlib import Path

import pytest

from h2h_lit.openai_provider import OpenAIResponsesProvider, _UrllibResponse
from h2h_lit.title_abstract_remaining_campaign import (
    ASSISTANCE_MODES,
    TASKS,
    VISUALIZATION_MODALITIES,
    choose_concurrency,
    taxonomy_coding_response_schema,
    validate_taxonomy_coding_payload,
)


def record(*, abstract: str = "Users visually compare clusters generated by statistical analysis."):
    return {
        "canonical_id": "canonical:test",
        "batch_order": 1,
        "prior_candidate_number": None,
        "title": "Visual cluster analysis",
        "abstract": abstract,
    }


def item(label, state="ABSENT", status="NOT_EVIDENCED_IN_SUPPLIED_METADATA", ids=None):
    return {
        "label": label,
        "state": state,
        "evidence_status": status,
        "evidence_ids": [] if ids is None else ids,
        "rationale": "Bound to supplied evidence or explicitly not evidenced.",
    }


def payload():
    return {
        "assistance_modes": [item(label) for label in ASSISTANCE_MODES],
        "visualization_modalities": [item(label) for label in VISUALIZATION_MODALITIES],
        "tasks": [item(label) for label in TASKS],
        "workflow_support_review": {
            "decision": "UNKNOWN",
            "evidence_status": "NOT_EVIDENCED_IN_SUPPLIED_METADATA",
            "evidence_ids": [],
            "rationale": "The supplied evidence does not resolve the workflow connection.",
        },
        "overall_rationale": "Provisional title-and-abstract coding only.",
    }


def test_schema_freezes_exact_vocabulary():
    schema = taxonomy_coding_response_schema()
    assert schema["properties"]["assistance_modes"]["minItems"] == len(ASSISTANCE_MODES)
    assert schema["properties"]["visualization_modalities"]["minItems"] == len(VISUALIZATION_MODALITIES)
    assert schema["properties"]["tasks"]["minItems"] == len(TASKS)


def test_unknown_and_absent_evidence_are_valid_and_non_dispositive():
    result = validate_taxonomy_coding_payload(payload(), record())
    assert result["workflow_support_review"]["decision"] == "UNKNOWN"
    assert result["screening_outcome_changed"] is False


def test_present_requires_valid_supplied_evidence_id():
    value = payload()
    value["assistance_modes"][0] = item(
        "Algorithmic", "PRESENT", "EVIDENCED", ["ABSTRACT.001"]
    )
    result = validate_taxonomy_coding_payload(value, record())
    assert result["assistance_modes"][0]["evidence"][0]["text"].startswith("Users")
    value["assistance_modes"][0]["evidence_ids"] = ["abstract.sentence.999"]
    with pytest.raises(ValueError, match="nonexistent"):
        validate_taxonomy_coding_payload(value, record())


def test_duplicate_or_missing_frozen_labels_are_rejected():
    value = payload()
    value["tasks"][-1] = dict(value["tasks"][0])
    with pytest.raises(ValueError, match="coverage or uniqueness"):
        validate_taxonomy_coding_payload(value, record())


def test_unsupported_workflow_is_flag_only_and_requires_evidence():
    value = payload()
    value["workflow_support_review"] = {
        "decision": "UNSUPPORTED",
        "evidence_status": "EVIDENCED",
        "evidence_ids": ["TITLE.1"],
        "rationale": "The supplied title affirmatively describes no integrated analysis.",
    }
    result = validate_taxonomy_coding_payload(value, record())
    assert result["screening_outcome_changed"] is False
    assert result["workflow_support_review"]["evidence"][0]["id"] == "TITLE.1"


@pytest.mark.parametrize(
    ("current", "clean", "headers", "throttled", "expected"),
    [
        (4, 40, {}, False, 8),
        (8, 40, {}, False, 8),
        (8, 40, {"x-ratelimit-limit-tokens": "500000", "x-ratelimit-limit-requests": "500"}, False, 16),
        (16, 40, {"x-ratelimit-limit-tokens": "2000000", "x-ratelimit-limit-requests": "5000"}, False, 32),
        (32, 0, {}, True, 16),
    ],
)
def test_controlled_concurrency_ramp(current, clean, headers, throttled, expected):
    assert choose_concurrency(current, clean_completions=clean, rate_limit_headers=headers, throttled=throttled) == expected


class FakeResponse:
    headers = {"x-ratelimit-limit-tokens": "500000", "authorization": "secret"}

    def raise_for_status(self):
        return None

    def json(self):
        return {
            "id": "resp_test",
            "status": "completed",
            "model": "gpt-5.6-luna",
            "service_tier": "default",
            "usage": {"input_tokens": 10, "output_tokens": 10},
            "output": [{"type": "message", "content": [{"type": "output_text", "text": "{}"}]}],
        }


class FakeSession:
    def post(self, *args, **kwargs):
        return FakeResponse()


def test_provider_persists_only_allowlisted_rate_limit_headers():
    provider = OpenAIResponsesProvider(api_key="not-real", session=FakeSession())
    provider.generate(
        model="gpt-5.6-luna",
        prompt="prompt",
        input_snapshot={},
        parameters={"response_schema_version": "coding-1.0.0"},
        request_id="request:test",
        attempt_number=1,
    )
    headers = provider.metadata_for("request:test", 1)["rate_limit_headers"]
    assert headers == {"x-ratelimit-limit-tokens": "500000"}
    assert "authorization" not in headers


def test_urllib_response_remains_compatible_with_no_headers():
    assert _UrllibResponse(b'{"ok":true}').json() == {"ok": True}
